use crate::app::message::design::editor;
use crate::app::views::design::models::{
    ColorFormat, ColorPickerTarget, DesignDoc, DesignElement, DesignTool, StickyNoteKind,
};
use crate::app::views::design::state::{
    DesignGenerationDevice, DesignGenerationTheme, DesignPlannerCorner, DesignPlannerTab,
    DesignSettingsTab, ImageImportTarget,
};
use iced::widget::text_editor::Action;
use iced::{Color, Point};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LayerAction {
    ToggleVisible,
    MoveUp,
    MoveDown,
    Delete,
}

impl std::fmt::Display for LayerAction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LayerAction::ToggleVisible => write!(f, "👁"),
            LayerAction::MoveUp => write!(f, "↑"),
            LayerAction::MoveDown => write!(f, "↓"),
            LayerAction::Delete => write!(f, "🗑"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PageAction {
    Rename,
    Duplicate,
    Delete,
    MoveUp,
    MoveDown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CanvasContextMenuAction {
    Cut,
    Copy,
    Paste,
    Delete,
    MoveUp,
    MoveDown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VariableKindPreset {
    Color,
    Number,
    String,
}

impl VariableKindPreset {
    pub fn as_kind(self) -> &'static str {
        match self {
            Self::Color => "color",
            Self::Number => "number",
            Self::String => "string",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::Color => "Color",
            Self::Number => "Number",
            Self::String => "String",
        }
    }

    pub fn default_name_prefix(self) -> &'static str {
        match self {
            Self::Color => "--color",
            Self::Number => "--number",
            Self::String => "--string",
        }
    }

    pub fn default_value(self) -> &'static str {
        match self {
            Self::Color => "#D4D4D8",
            Self::Number => "0",
            Self::String => "value",
        }
    }
}

#[derive(Debug, Clone)]
pub enum DesignMessage {
    ElementSelected(String),
    LayerRowPressed(String),
    MultiSelect(Vec<String>),
    Pan(iced::Vector),
    Zoom(f32, Option<iced::Point>),
    ToggleNode(String),
    ToolSelected(DesignTool),
    CreateElement {
        element: DesignElement,
        parent_id: Option<String>,
        start_editing: bool,
    },
    ZoomIn,
    ZoomOut,
    ZoomFit,
    ZoomSet(f32),
    ZoomPresetSelected(String),
    FitToElement(String),
    SetActiveGroup(u32),
    NewGroupNameChanged(String),
    CreateGroup,
    PageMenuToggle(u32, f32, f32),
    PageMenuClose,
    PageActionSelected(u32, PageAction),
    PageRenameChanged(String),
    PageRenameSubmit,
    PageRenameCancel,
    PropertyUpdate(String, String, serde_json::Value),
    PropertiesUpdate(String, Vec<(String, serde_json::Value)>),
    BatchPropertiesUpdate(Vec<(String, Vec<(String, serde_json::Value)>)>),
    // Transient updates (do not trigger snapshot, for continuous interactions like drag)
    PropertyUpdateTransient(String, String, serde_json::Value),
    PropertiesUpdateTransient(String, Vec<(String, serde_json::Value)>),
    BatchPropertiesUpdateTransient(Vec<(String, Vec<(String, serde_json::Value)>)>),
    EraseBrushAt(Point, f32),
    ContextEditorAction(Action),
    ToggleContextEditor,
    ContentEditorAction(Action),
    SelectFill(Option<usize>),
    SelectEffect(Option<usize>),
    ToggleVariables,
    SelectVariableCollection(String),
    ToggleVariableCollectionMenu(String),
    CloseVariableCollectionMenu,
    AddVariableCollection,
    RenameVariableCollectionRequested(String),
    VariableCollectionRenameChanged(String),
    SubmitVariableCollectionRename,
    CancelVariableCollectionRename,
    DuplicateVariableCollection(String),
    RequestDeleteVariableCollection(String),
    ConfirmDeleteVariableCollection,
    CancelDeleteVariableCollection,
    SelectVariableTheme(String),
    ToggleVariableThemeMenu(String),
    CloseVariableThemeMenu,
    AddVariableTheme,
    ToggleAddVariableMenu,
    CloseAddVariableMenu,
    CreateVariable(VariableKindPreset),
    ToggleVariableMenu(String),
    CloseVariableMenu,
    ToggleVariableMoveTargets(String),
    RenameVariableRequested(String),
    VariableRenameChanged(String),
    SubmitVariableRename,
    CancelVariableRename,
    DuplicateVariable(String),
    MoveVariableTo(String, Option<String>),
    RequestDeleteVariable(String),
    ConfirmDeleteVariable,
    CancelDeleteVariable,
    VariableValueChanged(String, Option<String>, String),
    RenameVariableThemeRequested(String),
    VariableThemeRenameChanged(String),
    SubmitVariableThemeRename,
    CancelVariableThemeRename,
    DuplicateVariableTheme(String),
    RequestDeleteVariableTheme(String),
    ConfirmDeleteVariableTheme,
    CancelDeleteVariableTheme,
    ToggleShortcuts,
    ToggleSettings,
    DesignSettingsSelectTab(DesignSettingsTab),
    ToggleMouseWheelZoom(bool),
    ToggleSlotContent(bool),
    ToggleSlotOverflow(bool),
    ToggleZoomMenu,
    ToggleContextPopover(Option<crate::app::views::design::state::ContextPopoverType>),
    ContextShapeGroupHover(Option<String>),
    UpdateContextShape(String),
    UpdateContextFill(String),
    UpdateContextBorder(String),
    CanvasContextMenuOpen(Point, Option<String>),
    CanvasContextMenuClose,
    CanvasContextMenuAction(CanvasContextMenuAction),
    ToggleLayerPanel,
    TogglePropertiesPanel,
    LayerPanelResizing(f32),
    ToggleVisible(String),
    MoveLayerItem(String, i32),
    LayerActionSelected(String, LayerAction),
    LayerDragStart(String),
    LayerDragOver(String),
    LayerDrop,
    LayerHover(String),
    LayerHoverLeave,
    LayerMenuHover(String),
    LayerMenuLeave,
    LayerMenuToggle(String, f32, f32),
    LayerMenuClose,
    EditStart(String, String),
    EditContentChanged(String),
    EditEditorAction(Action),
    EditSubmit,
    EditCancel,
    New,
    Open,
    ParseFigma,
    Save,
    SaveAs,
    ExportHtml,
    ExportElementHtml(String),
    ExportElementSvg(String),
    ShowHelpModal(String),
    CloseHelpModal,
    ExportElementPng(String),
    ExportElementJpeg(String),
    ViewElementHtml(String),
    HtmlPreviewAction(Action),
    CloseHtmlPreview,
    FileOpened(Result<(DesignDoc, Option<std::path::PathBuf>), String>),
    FileSaved(Option<std::path::PathBuf>),
    OpenColorPicker(Color, ColorPickerTarget, Option<Point>),
    OpenFillPicker(String, usize, Option<Point>),
    CloseFillPicker,
    OpenEffectPicker(String, usize, Option<Point>),
    CloseEffectPicker,
    OpenFontPicker(String, Option<Point>),
    CloseFontPicker,
    FontPickerSelect(String, String),
    OpenIconPicker(String, Option<Point>),
    CloseIconPicker,
    SetIconPickerFilter(String),
    SetIconPickerFamilyTab(String),
    IconFamilySelected {
        element_id: String,
        family: String,
    },
    IconPickerSelect {
        element_id: String,
        family: String,
        name: String,
    },
    FillPickerColorChange(Color),
    FillPickerFormatChange(ColorFormat),
    FillPickerEyedropper,
    ColorPickerChange(Color),
    ColorPickerFormatChange(ColorFormat),
    ColorPickerEyedropper,
    PickColor(iced::Point),
    CloseColorPicker,
    SetTailwindFilter(String),
    SetFontFilter(String),
    SetIconFilter(String),
    SetToolbarIconFamilyTab(String),
    SelectToolbarIcon {
        family: String,
        name: String,
    },
    SetBrushColor(String),
    SetBrushWidth(f32),
    OpenTailwindClassPicker(String, Option<Point>),
    CloseTailwindClassPicker,
    TailwindClassInputChanged(String, String),
    TailwindClassInputSubmit(String),
    AddTailwindClassToken(String, String),
    ConvertHtmlToLayers(String),
    // Canvas drag & reparent: ids to move, target parent frame (None for root)
    ReparentElements(Vec<String>, Option<String>),
    MeshCurveChanged(String, usize, serde_json::Value),
    // Tailwind
    SelectTailwindNode(String, Vec<usize>),
    ToggleTailwindInspectorCollapsed,
    ToggleTailwindTreeCollapsed(String, Vec<usize>),
    TailwindInspectorHover(bool),
    TailwindNodeClassEditorAction(Action),
    TailwindNodeClassInputChanged(String, Vec<usize>, String),
    TailwindNodeClassInputSubmit(String, Vec<usize>),
    TailwindNodeClassDropdownClose(String, Vec<usize>),
    TailwindNodeClassCommit(String, Vec<usize>),
    UpdateTailwindNodeClass(String, Vec<usize>, String),
    TailwindNodeTextEditorAction(Action),
    TailwindNodeTextCommit(String, Vec<usize>),
    UpdateTailwindNodeText(String, Vec<usize>, String),
    UpdateTailwindHtml(String, String),
    TailwindHtmlEditorAction(Action),
    DeleteTailwindNode(String, Vec<usize>),
    ImageLoaded(String, Result<(iced::widget::image::Handle, Option<(u32, u32)>), String>),
    ImportImageElement,
    ImportFillImage(String, usize),
    CloseImageImportDialog,
    OpenStickyNoteDialog,
    CloseStickyNoteDialog,
    CreateStickyNote(StickyNoteKind),
    ImageImportInputChanged(String),
    PasteImageImportInput,
    ImageImportClipboardReceived(Option<String>),
    ChooseImageImportFile,
    SubmitImageImport,
    ImageImportFilePicked(Result<Option<ImageImportPayload>, String>),
    ImageImportResolved(Result<ImageImportPayload, String>),
    FigmaImportFilePicked(Option<std::path::PathBuf>),
    FigmaFileImported(Result<Option<crate::app::views::design::models::DesignDoc>, String>),
    FigmaParseCompleted(Result<Option<std::path::PathBuf>, String>),
    FigmaProgressTick,
    Undo,
    Redo,
    Cut,
    Copy,
    Paste,
    ClipboardContentReceived(Option<String>),
    DesignGenerationPromptAction(Action),
    DesignGenerationLogEditorAction(Action),
    DesignGenerationCopyChatMessage(usize),
    DesignGenerationSelectChatMessage(usize),
    DesignGenerationClearChatSelection,
    DesignGenerationShowAllLogs,
    DesignGenerationLoadLogFiles,
    DesignGenerationLogFilesLoaded(Vec<String>),
    ToggleDesignGenerationExecutorPopover,
    CloseDesignGenerationExecutorPopover,
    DesignGenerationAcpAgentSelected(Option<String>),
    ToggleDesignGenerationThemePopover,
    CloseDesignGenerationThemePopover,
    ToggleDesignGenerationDevicePopover,
    CloseDesignGenerationDevicePopover,
    ToggleDesignGenerationStylePopover,
    CloseDesignGenerationStylePopover,
    DesignGenerationDeviceSelected(DesignGenerationDevice),
    DesignGenerationStyleSelected(crate::app::views::design::state::DesignStyle),
    ToggleDesignGenerationModelPopover,
    CloseDesignGenerationModelPopover,
    DesignGenerationModelSelected(String),
    DesignGenerationModelChanged(String),
    DesignGenerationParallelPagesChanged(String),
    DesignGenerationThemeSelected(DesignGenerationTheme),
    DesignGenerationSubmit,
    DesignGenerationCancel,
    ToggleDesignPlannerPanelCollapsed,
    DesignPlannerSelectTab(DesignPlannerTab),
    OpenDesignPlannerQuickMenu,
    CloseDesignPlannerQuickMenu,
    DesignPlannerSetCorner(DesignPlannerCorner),
    DesignPlannerNewChatSession,
    DesignPlannerSelectChatSession(usize),
    DesignGenerationApplyPartialRegenerate,
    DesignGenerationStreamTick,
    DesignGenerationCompleted(Result<editor::DesignPlanExecutionResult, String>),
    GenerateDesignPage(String, String),
    RegenerateDesignPage(String, String),
    SetDesignPageTargetFrame(String, String, String),
    AggregateDesignPage(String, String),
    SaveDesignProjectPen,
    DesignProjectPenSaved(Result<Option<std::path::PathBuf>, String>),
    SaveGeneratedPageAsPen(String, String),
    GeneratedPagePenSaved(Result<Option<std::path::PathBuf>, String>),
    ImportGeneratedPenToPage(String, String),
    DesignPageGenerated {
        page_frame_id: String,
        page_task_id: String,
        result: Result<editor::DesignModuleExecutionResult, String>,
    },
    GeneratedPagePenImported {
        page_frame_id: String,
        page_task_id: String,
        result: Result<crate::app::views::design::models::DesignDoc, String>,
    },
    Snapshot,
}

#[derive(Debug, Clone)]
pub struct ImageImportPayload {
    pub target: ImageImportTarget,
    pub source: String,
    pub bytes: Vec<u8>,
    pub size_opt: Option<(u32, u32)>,
}
