//! 定义任务看板消息类型，作为界面事件与状态更新之间的契约。
//!
//! 注释说明当前文件的职责边界，帮助调用方理解数据流与错误传播，
//! 不改变任何运行时行为。

use super::*;

#[derive(Debug, Clone)]
/// 描述 TaskBoardMessage 支持的离散状态或消息分支。
pub enum TaskBoardMessage {
    ToggleBoard,
    CloseBoard,
    LoadTasks,
    TasksLoaded(Vec<Task>),
    CreateTask,
    CreateTaskSubmitted,
    AddTaskFromInput(String),
    AddTaskFromInputWithOptions {
        content: String,
        priority: String,
        model: String,
        subtasks: Vec<String>,
    },
    CreateTaskCancelled,
    OpenSettingsModal,
    CloseSettingsModal,
    SelectSettingsModalTab(TaskBoardSettingsModalTab),
    UpdateDraftPriority(String),
    UpdateDraftAssignee(String),
    UpdateDraftModel(String),
    UpdateDraftAgent(Option<String>),
    UpdateDraftExecutor(Option<String>),
    UpdateDraftDescription(String),
    UpdateDraftPrompt(String),
    UpdateDraftSubtask {
        index: usize,
        value: String,
    },
    AddDraftSubtask,
    RemoveDraftSubtask(usize),
    MoveDraftSubtaskUp(usize),
    MoveDraftSubtaskDown(usize),
    UpdateDraftAutoPromoteDelay(String),
    TaskCreated(Task),
    TaskStatusChanged {
        task_id: String,
        new_status: TaskStatus,
    },
    TaskUpdated(Task),
    TaskDeleted(String),
    TaskArchived(String),
    ArchiveCompletedTasks,
    ToggleTaskSelection {
        task_id: String,
        selected: bool,
    },
    ToggleBulkSelectionMode(TaskStatus),
    SelectAllTasksInStatus(TaskStatus),
    InvertTaskSelectionInStatus(TaskStatus),
    UpdateBulkPriorityInput(String),
    UpdateBulkModelInput(String),
    BulkAgentSelected(String),
    BulkSetPriorityInStatus(TaskStatus),
    BulkSetModelInStatus(TaskStatus),
    BulkSetAgentInStatus(TaskStatus),
    BulkSetExecutorInStatus {
        status: TaskStatus,
        executor: Option<String>,
    },
    ToggleBulkExecutorPopover,
    BulkExecutorSelected(Option<String>),
    CloseBulkExecutorPopover,
    BulkArchiveTasksInStatus(TaskStatus),
    BulkDeleteTasksInStatus(TaskStatus),
    BulkMoveTasksInStatus {
        from_status: TaskStatus,
        to_status: TaskStatus,
    },
    BulkActionCompleted(Result<(), String>),
    DuplicateTask(String),
    DragStarted {
        task_id: String,
        from_status: TaskStatus,
    },
    DragPending {
        task_id: String,
        from_status: TaskStatus,
        press_position: iced::Point,
    },
    CardReleased {
        task_id: String,
    },
    DragEnded,
    DropOnStatus {
        to_status: TaskStatus,
        insert_index: Option<usize>,
    },
    SelectTask(String),
    DeselectTask,
    ViewTaskLogs(String),
    CloseTaskLogs,
    EditTask(String),
    UpdateEditingTaskPriority(String),
    UpdateEditingTaskModel(String),
    UpdateEditingTaskModelInput(String),
    UpdateEditingTaskAgent(Option<String>),
    UpdateEditingTaskExecutor(Option<String>),
    UpdateEditingTaskPrompt(String),
    SaveEditingTask,
    CloseTaskPanel,
    ToggleAutoExecute(bool),
    SetMaxConcurrent(u32),
    ToggleAutoRefresh(bool),
    SetRefreshIntervalSeconds(u64),
    SetSchedulerTickIntervalSeconds(u64),
    SetAutoPromoteTickIntervalSeconds(u64),
    SetFailedRetryMinutes(u32),
    SetRunningTimeoutMinutes(u32),
    ToggleRecycleWorktreeOnTaskFinish(bool),
    SetPrSubmittedStallTimeoutSeconds(u32),
    StartExecution,
    StopExecution,
    ExecutionTick,
    WorktreePoolMaintained {
        result: Result<(usize, usize), String>,
    },
    WorktreeSnapshotLoaded(Option<crate::app::task::WorktreePoolSnapshot>),
    AutoCodeReviewTick,
    UiTick,
    SimulateStep {
        task_id: String,
    },
    ExecuteTask {
        task_id: String,
    },
    TaskExecutionCompleted {
        task_id: String,
        result: Result<String, String>,
    },
    TaskPlanningCompleted {
        task_id: String,
        result: Result<crate::app::task::TaskPlanGenerationOutcome, String>,
    },
    TaskCodeReviewCompleted {
        task_id: String,
        result: Result<String, String>,
    },
    TaskMergeCompleted {
        task_id: String,
        result: Result<String, String>,
    },
    TaskWorktreeRecycled {
        task_id: String,
        result: Result<(), String>,
    },
    TaskWorktreeReleased {
        task_id: String,
        result: Result<(), String>,
    },
    CleanAllWorktreesPressed,
    CleanAllWorktreesCompleted(Result<usize, String>),
    DeleteAllWorktreesPressed,
    DeleteAllWorktreesCompleted(Result<usize, String>),
    CommitMergeAllWorktreesPressed,
    CommitMergeAllWorktreesCompleted(Result<usize, String>),
    CancelWorktreeManualConfirm,
    WorktreeActionLogTick,
    ColumnScrollChanged {
        status: TaskStatus,
        has_vertical_scrollbar: bool,
    },
    FilterByStatus(Option<TaskStatus>),
    FilterByPriority(Option<(u32, u32)>),
    SortByPriority(bool),
    SortByDate(bool),
    SettingsUpdated(TaskBoardSettings),
    OpenTaskInSession {
        task_id: String,
    },
    ContextMenuOpened {
        task_id: String,
        x: f32,
        y: f32,
    },
    ContextMenuClosed,
    ToggleAutoPromotePoolTasks(bool),
    SetAutoPromoteDelay(u64),
    AddSubTask {
        task_id: String,
        content: String,
    },
    RemoveSubTask {
        task_id: String,
        subtask_id: String,
    },
    MoveSubTaskUp {
        task_id: String,
        subtask_id: String,
    },
    MoveSubTaskDown {
        task_id: String,
        subtask_id: String,
    },
    ToggleSubTaskCompleted {
        task_id: String,
        subtask_id: String,
    },
    UpdateSubTaskContent {
        task_id: String,
        subtask_id: String,
        content: String,
    },
    SubTaskUpdated {
        task_id: String,
        subtasks: Vec<SubTask>,
    },
    PromotePoolTasksTick,
    PoolTasksScheduled(
        Result<vw_gateway_client::vw_api_types::task::TaskPoolScheduleResponse, String>,
    ),
    UpdateNewSubtaskContent(String),
    DescEditorAction(iced::widget::text_editor::Action),
    PromptEditorAction(iced::widget::text_editor::Action),
    LogsViewerEditorAction(iced::widget::text_editor::Action),
    LogsViewerEditorWheelScrolled {
        delta: iced::mouse::ScrollDelta,
        viewport_height: f32,
    },
    LogsViewerScrollbarChanged {
        top_line: f32,
        viewport_height: f32,
    },
    LogsViewerOpenContextMenu {
        x: f32,
        y: f32,
    },
    LogsViewerCloseContextMenu,
    LogsViewerContextMenuCopy,
    LogsViewerContextMenuCut,
    LogsViewerContextMenuPaste,
    LogsViewerContextMenuDelete,
    ToggleModelPopover,
    ModelSelected(String),
    CloseModelPopover,
    ToggleBulkModelPopover,
    BulkModelSelected(String),
    CloseBulkModelPopover,
    ToggleExecutorPopover,
    ToggleWorktreePanelExpanded,
    ToggleWorktreePixelOffice(bool),
    ToggleCodeReview(bool),
    ToggleClearPromptAfterCreate(bool),
    ToggleCloseAfterCreate(bool),
    ToggleCloseAfterEdit(bool),
    ClearCreateSubmitSuccess,
    ClearEditSubmitSuccess,
    EditingTaskSaved(Result<(), String>),
    ToggleImportMode(bool),
    ImportEditorAction(iced::widget::text_editor::Action),
    ImportFilePick,
    ImportFilePicked(Option<String>),
    ImportFileLoaded(Result<String, String>),
    InsertDemoData(String),
    SetImportPromptFormat(TaskImportPromptFormat),
    ToggleImportPromptCollapsed,
    CopyImportPromptTemplate,
    ClearImportEditor,
    ImportTasksSubmitted,
}
#[cfg(test)]
#[path = "message_tests.rs"]
mod message_tests;
