use super::{
    GatewayRedisConnectionTestResponse, RedisCommandOutputEntry, RedisConnectionTab,
    RedisDetailTab, RedisKeyAnalysis, RedisKeyPage, RedisKeyValueKind, RedisRuntimeOverview,
    RedisToolGatewaySnapshot,
};

/// Redis 工具消息。
#[derive(Debug, Clone)]
pub enum RedisToolMessage {
    OpenSettingsModal,
    CloseSettingsModal,
    OpenHistoryModal,
    CloseHistoryModal,
    OpenConnectionModal,
    CloseConnectionModal,
    NewConnection,
    SearchConnectionsChanged(String),
    SelectConnection(String),
    SelectConnectionCompleted(
        Result<
            (
                RedisToolGatewaySnapshot,
                Option<Result<RedisRuntimeOverview, String>>,
                Option<Result<RedisKeyPage, String>>,
            ),
            String,
        >,
    ),
    DetailTabChanged(RedisDetailTab),
    RefreshSelectedRuntime,
    ReloadSelectedKeys,
    LoadMoreKeys,
    OpenCreateKeyModal,
    CloseCreateKeyModal,
    CreateKeyNameChanged(String),
    CreateKeyTypeChanged(RedisKeyValueKind),
    ConfirmCreateKey,
    CreateKeyCompleted {
        connection_id: String,
        key: String,
        result: Result<RedisKeyAnalysis, String>,
    },
    SelectKey(String),
    RefreshSelectedKeyAnalysis,
    KeyAnalysisLoaded {
        connection_id: String,
        key: String,
        result: Result<RedisKeyAnalysis, String>,
    },
    RuntimeLoaded {
        connection_id: String,
        success_message: Option<String>,
        result: Result<RedisRuntimeOverview, String>,
    },
    KeyPageLoaded {
        connection_id: String,
        append: bool,
        result: Result<RedisKeyPage, String>,
    },
    DraftNameChanged(String),
    DraftHostChanged(String),
    DraftPortChanged(String),
    DraftDbChanged(String),
    DraftUsernameChanged(String),
    DraftPasswordChanged(String),
    DraftTabChanged(RedisConnectionTab),
    DraftTlsToggled(bool),
    DraftTlsPrivateKeyPathChanged(String),
    DraftTlsPublicCertPathChanged(String),
    DraftTlsCaCertPathChanged(String),
    PickTlsPrivateKeyFile,
    TlsPrivateKeyFilePicked(Option<String>),
    PickTlsPublicCertFile,
    TlsPublicCertFilePicked(Option<String>),
    PickTlsCaCertFile,
    TlsCaCertFilePicked(Option<String>),
    DraftSshEnabledToggled(bool),
    DraftSshHostChanged(String),
    DraftSshPortChanged(String),
    DraftSshUsernameChanged(String),
    DraftSshPasswordChanged(String),
    DraftSshPrivateKeyPathChanged(String),
    PickSshPrivateKeyFile,
    SshPrivateKeyFilePicked(Option<String>),
    DraftSshPassphraseChanged(String),
    DraftSshTimeoutSecsChanged(String),
    DraftSentinelEnabledToggled(bool),
    DraftSentinelMasterNameChanged(String),
    DraftSentinelNodePasswordChanged(String),
    DraftClusterToggled(bool),
    DraftReadOnlyToggled(bool),
    DraftKeyPatternChanged(String),
    SaveDraft,
    SaveDraftCompleted(Result<RedisToolGatewaySnapshot, String>),
    DeleteSelected,
    TestSelected,
    TestSelectedCompleted(
        Result<(GatewayRedisConnectionTestResponse, RedisToolGatewaySnapshot), String>,
    ),
    CopySelectedUri,
    ExportConfigs,
    ExportCompleted(Result<Option<RedisToolGatewaySnapshot>, String>),
    ImportConfigs,
    ImportCompleted(Result<Option<RedisToolGatewaySnapshot>, String>),
    DefaultLoadCountChanged(String),
    SaveDefaultLoadCount,
    IncreaseDefaultLoadCount,
    DecreaseDefaultLoadCount,
    CommandInputChanged(String),
    RunCommand,
    CommandCompleted {
        connection_id: String,
        result: Result<RedisCommandOutputEntry, String>,
    },
    KeyBrowserPatternChanged(String),
    ToggleKeyTreePath(String),
    InfoFilterChanged(String),
    HistoryPreviousPage,
    HistoryNextPage,
    HistoryFilterChanged(String),
    HistoryOnlyWriteToggled(bool),
    SnapshotLoaded {
        success_message: Option<String>,
        result: Result<RedisToolGatewaySnapshot, String>,
    },
    ClearNotification,
    ClearGatewayError,
}

#[cfg(test)]
#[path = "message_tests.rs"]
mod message_tests;
