//! 思维导图经典主题族定义，提供克制且通用的节点配色方案。

use super::MindMapTheme;

pub(crate) const CLASSIC_VARIANTS: [MindMapTheme; 8] = [
    MindMapTheme {
        id: "classic:0",
        name: "经典推荐",
        background_color: 0xFFFFFFFF,
        root_fill: 0x8B4513FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x98FB98FF],
        branch_text: 0x111827FF,
        leaf_fill: 0x98FB98FF,
        leaf_text: 0x111827FF,
        line_color: Some(0x98FB98FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "classic:1",
        name: "经典推荐",
        background_color: 0xFFFFFFFF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x111827FF,
        branch_fills: &[0xFF4500FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0xFFA500FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "classic:2",
        name: "经典推荐",
        background_color: 0xF0F0F0FF,
        root_fill: 0x32CD32FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0xA9A9A9FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "classic:3",
        name: "经典推荐",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E90FFFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xD3D3D3FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xD3D3D3FF,
        leaf_text: 0x111827FF,
        line_color: Some(0x1E90FFFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "classic:4",
        name: "经典推荐",
        background_color: 0xFFFFFFFF,
        root_fill: 0x2C3E50FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xBDC3C7FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0x2C3E50FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "classic:5",
        name: "经典推荐",
        background_color: 0xFFFFFFFF,
        root_fill: 0x8A2BE2FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xD8BFD8FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xD8BFD8FF,
        leaf_text: 0x111827FF,
        line_color: None,
        is_dark: false,
    },
    MindMapTheme {
        id: "classic:6",
        name: "经典推荐",
        background_color: 0x4B0082FF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x111827FF,
        branch_fills: &[0x32CD32FF],
        branch_text: 0x111827FF,
        leaf_fill: 0x32CD32FF,
        leaf_text: 0x111827FF,
        line_color: Some(0x32CD32FF),
        is_dark: true,
    },
    MindMapTheme {
        id: "classic:7",
        name: "经典推荐",
        background_color: 0x333333FF,
        root_fill: 0xFF8C00FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0xFFFFFFFF),
        is_dark: true,
    },
];

pub(crate) const RETRO_VARIANTS: [MindMapTheme; 8] = [
    MindMapTheme {
        id: "retro:0",
        name: "复古彩虹",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFF8C00FF,
        leaf_text: 0x111827FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "retro:1",
        name: "复古彩虹",
        background_color: 0x0B1F35FF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x111827FF,
        branch_fills: &[0x32CD32FF],
        branch_text: 0x111827FF,
        leaf_fill: 0x1E90FFFF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0xFFFFFFFF),
        is_dark: true,
    },
    MindMapTheme {
        id: "retro:2",
        name: "复古彩虹",
        background_color: 0xE0F2FEFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "retro:3",
        name: "复古彩虹",
        background_color: 0xFFFFFFFF,
        root_fill: 0x8A2BE2FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0x8A2BE2FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "retro:4",
        name: "复古彩虹",
        background_color: 0x2B1B14FF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x2C3E50FF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x2C3E50FF,
        leaf_fill: 0xECF0F1FF,
        leaf_text: 0x2C3E50FF,
        line_color: Some(0x2C3E50FF),
        is_dark: true,
    },
    MindMapTheme {
        id: "retro:5",
        name: "复古彩虹",
        background_color: 0xF5F0E6FF,
        root_fill: 0xDAA520FF,
        root_text: 0x111827FF,
        branch_fills: &[0xA9A9A9FF],
        branch_text: 0x111827FF,
        leaf_fill: 0x808080FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0xDAA520FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "retro:6",
        name: "复古彩虹",
        background_color: 0x3B0A57FF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x111827FF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0xFFFFFFFF),
        is_dark: true,
    },
    MindMapTheme {
        id: "retro:7",
        name: "复古彩虹",
        background_color: 0xFFFFFFFF,
        root_fill: 0x2C3E50FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x8A2BE2FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xA9A9A9FF,
        leaf_text: 0x111827FF,
        line_color: Some(0x8A2BE2FF),
        is_dark: false,
    },
];

pub(crate) const VITALITY_VARIANTS: [MindMapTheme; 8] = [
    MindMapTheme {
        id: "vitality:0",
        name: "活力幻彩",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "vitality:1",
        name: "活力幻彩",
        background_color: 0x4B0082FF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x111827FF,
        branch_fills: &[0x8A2BE2FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0x8A2BE2FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: true,
    },
    MindMapTheme {
        id: "vitality:2",
        name: "活力幻彩",
        background_color: 0xFFFFFFFF,
        root_fill: 0x32CD32FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x8A2BE2FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xDDA0DDFF,
        leaf_text: 0x111827FF,
        line_color: Some(0x32CD32FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "vitality:3",
        name: "活力幻彩",
        background_color: 0xFFFFFFFF,
        root_fill: 0x8A2BE2FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "vitality:4",
        name: "活力幻彩",
        background_color: 0xDDA0DDFF,
        root_fill: 0x8A2BE2FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "vitality:5",
        name: "活力幻彩",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "vitality:6",
        name: "活力幻彩",
        background_color: 0x1E3A5FFF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x111827FF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: true,
    },
    MindMapTheme {
        id: "vitality:7",
        name: "活力幻彩",
        background_color: 0x4B0082FF,
        root_fill: 0x32CD32FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0xADFF2FFF),
        is_dark: true,
    },
];
