//! 思维导图表现力主题族定义，提供更鲜明的节点和边线配色方案。

use super::MindMapTheme;

pub(crate) const ROSE_VARIANTS: [MindMapTheme; 8] = [
    MindMapTheme {
        id: "rose:0",
        name: "紫红魅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "rose:1",
        name: "紫红魅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x1E3A5FFF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0x7C3AEDFF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "rose:2",
        name: "紫红魅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x7C3AEDFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xF9A8D4FF],
        branch_text: 0x374151FF,
        leaf_fill: 0xF9A8D4FF,
        leaf_text: 0x374151FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "rose:3",
        name: "紫红魅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "rose:4",
        name: "紫红魅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "rose:5",
        name: "紫红魅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0xD946EFFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xD946EFFF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xC4B5FDFF,
        leaf_text: 0x374151FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "rose:6",
        name: "紫红魅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "rose:7",
        name: "紫红魅丽",
        background_color: 0xEF4444FF,
        root_fill: 0xFFFFFFFF,
        root_text: 0xB91C1CFF,
        branch_fills: &[0xF9A8D4FF],
        branch_text: 0x374151FF,
        leaf_fill: 0xF9A8D4FF,
        leaf_text: 0x374151FF,
        line_color: Some(0xFFFFFFFF),
        is_dark: true,
    },
];

pub(crate) const CLASH_VARIANTS: [MindMapTheme; 8] = [
    MindMapTheme {
        id: "clash:0",
        name: "活力对撞",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "clash:1",
        name: "活力对撞",
        background_color: 0x000000FF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x1E3A5FFF,
        branch_fills: &[0xFDE047FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: true,
    },
    MindMapTheme {
        id: "clash:2",
        name: "活力对撞",
        background_color: 0xFFFFFFFF,
        root_fill: 0xFF8C00FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xD1D5DBFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "clash:3",
        name: "活力对撞",
        background_color: 0xFEF9C3FF,
        root_fill: 0x000000FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x22C55EFF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFEF9C3FF,
        leaf_text: 0x111827FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "clash:4",
        name: "活力对撞",
        background_color: 0xF3F4F6FF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "clash:5",
        name: "活力对撞",
        background_color: 0xFFFFFFFF,
        root_fill: 0x22C55EFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "clash:6",
        name: "活力对撞",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0x86EFACFF,
        leaf_text: 0x111827FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "clash:7",
        name: "活力对撞",
        background_color: 0x0B1F35FF,
        root_fill: 0x7C3AEDFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x93C5FDFF],
        branch_text: 0x111827FF,
        leaf_fill: 0x3B82F6FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: true,
    },
];
