//! 思维导图水果主题族定义，提供轻量、柔和的语义配色方案。

use super::MindMapTheme;

pub(crate) const CHERRY_VARIANTS: [MindMapTheme; 8] = [
    MindMapTheme {
        id: "cherry:0",
        name: "浪漫樱花",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "cherry:1",
        name: "浪漫樱花",
        background_color: 0xFFFFFFFF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x1E3A5FFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF8C00FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0xF9A8D4FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "cherry:2",
        name: "浪漫樱花",
        background_color: 0xFFFFFFFF,
        root_fill: 0xF9A8D4FF,
        root_text: 0x374151FF,
        branch_fills: &[0xF9A8D4FF],
        branch_text: 0x374151FF,
        leaf_fill: 0xF9A8D4FF,
        leaf_text: 0x374151FF,
        line_color: Some(0xF9A8D4FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "cherry:3",
        name: "浪漫樱花",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "cherry:4",
        name: "浪漫樱花",
        background_color: 0xFFFFFFFF,
        root_fill: 0xF9A8D4FF,
        root_text: 0x374151FF,
        branch_fills: &[0xF9A8D4FF],
        branch_text: 0x374151FF,
        leaf_fill: 0xF9A8D4FF,
        leaf_text: 0x374151FF,
        line_color: Some(0xF9A8D4FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "cherry:5",
        name: "浪漫樱花",
        background_color: 0xFFFFFFFF,
        root_fill: 0xF9A8D4FF,
        root_text: 0x374151FF,
        branch_fills: &[0xF9A8D4FF],
        branch_text: 0x374151FF,
        leaf_fill: 0xFDE047FF,
        leaf_text: 0x374151FF,
        line_color: Some(0xF9A8D4FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "cherry:6",
        name: "浪漫樱花",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x1E3A5FFF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x1E3A5FFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "cherry:7",
        name: "浪漫樱花",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
];

pub(crate) const PURPLE_VARIANTS: [MindMapTheme; 8] = [
    MindMapTheme {
        id: "purple:0",
        name: "紫色果韵",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x1E3A5FFF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "purple:1",
        name: "紫色果韵",
        background_color: 0xFFFFFFFF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x111827FF,
        branch_fills: &[0x7C3AEDFF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0x7C3AEDFF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x7C3AEDFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "purple:2",
        name: "紫色果韵",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x1E3A5FFF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "purple:3",
        name: "紫色果韵",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "purple:4",
        name: "紫色果韵",
        background_color: 0xFFFFFFFF,
        root_fill: 0x7C3AEDFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0x7C3AEDFF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0x7C3AEDFF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x7C3AEDFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "purple:5",
        name: "紫色果韵",
        background_color: 0xFFFFFFFF,
        root_fill: 0x7C3AEDFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFDE047FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFDE047FF,
        leaf_text: 0x111827FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "purple:6",
        name: "紫色果韵",
        background_color: 0xFFFFFFFF,
        root_fill: 0x7C3AEDFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x1E3A5FFF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x1E3A5FFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "purple:7",
        name: "紫色果韵",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
];
