//! 思维导图专业主题族定义，提供适合工作场景的低干扰配色方案。

use super::MindMapTheme;

pub(crate) const BUSINESS_VARIANTS: [MindMapTheme; 6] = [
    MindMapTheme {
        id: "business:0",
        name: "简约商务",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "business:1",
        name: "简约商务",
        background_color: 0xFFFFFFFF,
        root_fill: 0x14B8A6FF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFEF08AFF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFEF08AFF,
        leaf_text: 0x111827FF,
        line_color: Some(0x93C5FDFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "business:2",
        name: "简约商务",
        background_color: 0xF3F4F6FF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "business:3",
        name: "简约商务",
        background_color: 0xFFFFFFFF,
        root_fill: 0xF5F5DCFF,
        root_text: 0x1E3A5FFF,
        branch_fills: &[0x000000FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0x000000FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "business:4",
        name: "简约商务",
        background_color: 0xFFFFFFFF,
        root_fill: 0xFDE047FF,
        root_text: 0x111827FF,
        branch_fills: &[0x7C3AEDFF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0x7C3AEDFF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0xFEF9C3FF),
        is_dark: false,
    },
    MindMapTheme {
        id: "business:5",
        name: "简约商务",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xCBD5E1FF],
        branch_text: 0x111827FF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x111827FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
];

pub(crate) const SOFT_VARIANTS: [MindMapTheme; 8] = [
    MindMapTheme {
        id: "soft:0",
        name: "柔和雅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xF9A8D4FF],
        branch_text: 0x374151FF,
        leaf_fill: 0xF9A8D4FF,
        leaf_text: 0x374151FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "soft:1",
        name: "柔和雅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0xFFFFFFFF,
        root_text: 0x1E3A5FFF,
        branch_fills: &[0x86EFACFF, 0xE5E7EBFF],
        branch_text: 0x374151FF,
        leaf_fill: 0xE5E7EBFF,
        leaf_text: 0x374151FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "soft:2",
        name: "柔和雅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFFFFFFFF],
        branch_text: 0x1E3A5FFF,
        leaf_fill: 0xFFFFFFFF,
        leaf_text: 0x1E3A5FFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "soft:3",
        name: "柔和雅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "soft:4",
        name: "柔和雅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF8C00FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "soft:5",
        name: "柔和雅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xD2B48CFF],
        branch_text: 0x374151FF,
        leaf_fill: 0xD2B48CFF,
        leaf_text: 0x374151FF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "soft:6",
        name: "柔和雅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
    MindMapTheme {
        id: "soft:7",
        name: "柔和雅丽",
        background_color: 0xFFFFFFFF,
        root_fill: 0x1E3A5FFF,
        root_text: 0xFFFFFFFF,
        branch_fills: &[0xFF8C00FF],
        branch_text: 0xFFFFFFFF,
        leaf_fill: 0xFF4500FF,
        leaf_text: 0xFFFFFFFF,
        line_color: Some(0x1E3A5FFF),
        is_dark: false,
    },
];
