//! 思维导图消息类型定义，集中描述视图、画布和状态更新事件。

use crate::app::views::design::models::ColorFormat;
use crate::apps::mindmap::state::{
    BracketLayoutFormat, EdgeStyle, FishboneLayoutFormat, MindMapCanvasTool, MindMapColorTarget,
    MindMapDiagramType, MindMapDoodleStroke, MindMapLayoutFormat, OrgChartLayoutFormat,
    TimelineLayoutFormat, TreeLayoutFormat,
};
use iced::widget::text_editor;
use iced::{Color, Point, Vector};

/// MindMapMessage 枚举，描述当前模块支持的有限状态或操作分支。
#[derive(Debug, Clone)]
pub enum MindMapMessage {
    New,
    Open,
    Save,
    SaveAs,
    SaveAsJson,
    ToggleExportMenu,
    ExportPng,
    ExportJpeg,
    ExportSvg,
    SaveFinished(Result<(), String>),
    ExportFinished(Result<(), String>),
    FileSaved(Option<String>),
    PanBy(Vector),
    Zoom(f32, Option<Point>),
    ZoomSet(f32),
    ZoomFit,
    ToggleZoomMenu,
    SelectNode(Vec<usize>),
    ClearSelection,
    NodeDragStart(Vec<usize>, Point, Point),
    NodeDragged(Vec<usize>, Vector),
    SetCanvasTool(MindMapCanvasTool),
    SetDoodleColor(u32),
    SetDoodleWidth(f32),
    DoodleCommit(MindMapDoodleStroke),
    DoodleErase(Point, f32),
    ClosePickers,
    ToggleActionMenu,
    TogglePriorityPicker,
    SetNodePriority(u8),
    ClearNodePriority,
    ToggleNodeUrlEditor,
    NodeUrlChanged(String),
    SaveNodeUrl,
    ClearNodeUrl,
    OpenNodeUrl,
    OpenNodeUrlAt(Vec<usize>),
    ToggleNodeTextEditor,
    NodeTextChanged(String),
    NodeTextEditorAction(text_editor::Action),
    NodeTextEditorEnter { shift: bool },
    SaveNodeText,
    OpenColorPicker(MindMapColorTarget, Color),
    ColorPickerChanged(Color),
    ColorPickerFormatChanged(ColorFormat),
    ResetColorTarget(MindMapColorTarget),
    SetBackground(Option<u32>),
    ToggleDiagramTypePicker,
    SelectDiagramType(MindMapDiagramType),
    SetDiagramType(MindMapDiagramType),
    SetLayoutFormat(MindMapLayoutFormat),
    SetOrgChartLayoutFormat(OrgChartLayoutFormat),
    SetFishboneLayoutFormat(FishboneLayoutFormat),
    SetTimelineLayoutFormat(TimelineLayoutFormat),
    SetBracketLayoutFormat(BracketLayoutFormat),
    SetTreeLayoutFormat(TreeLayoutFormat),
    ToggleThemePanel,
    SetThemeGroup(String),
    SetThemeVariant(String, usize),
    SaveThemeToCustom,
    DeleteCustomTheme(usize),
    CancelThemeBackground,
    SetEdgeStyle(EdgeStyle),
    SetNodeBorderStyle(EdgeStyle),
    ToggleMarkdownImport,
    MarkdownImportEditorAction(text_editor::Action),
    ApplyMarkdownImport,
    AddChild,
    AddSibling,
    AddChildAt(Vec<usize>),
    AddSiblingAt(Vec<usize>),
    ToggleCollapseAt(Vec<usize>),
    OpenNodeContextMenu(Vec<usize>, Point),
    CloseContextMenu,
    CutNode,
    CopyNode,
    PasteNode,
    DuplicateNode,
    DeleteNode,
    Undo,
    Redo,
    FileOpened(Result<(Option<String>, String), String>),
    LoadPersistedFinished(Result<Option<serde_json::Value>, String>),
}
