//! 记忆快照模块 —— 将核心记忆导出/导入为人类可读的 Markdown 格式。
//!
//! # 核心功能
//!
//! **原子灵魂导出（Atomic Soul Export）**：将 `MemoryCategory::Core` 类型的记忆从 SQLite 数据库
//! 导出到 `MEMORY_SNAPSHOT.md` 文件，使代理的"灵魂"始终在 Git 版本控制中可见。
//!
//! **自动水合（Auto-Hydration）**：如果 `brain.db` 数据库不存在但 `MEMORY_SNAPSHOT.md` 文件存在，
//! 系统会自动将所有条目重新索引到全新的 SQLite 数据库中。
//!
//! # 使用场景
//!
//! - 版本控制：将核心记忆提交到 Git 仓库，便于追踪和恢复
//! - 灾难恢复：当数据库丢失时，从快照文件快速恢复记忆
//! - 迁移：在不同环境间迁移代理的核心记忆

use anyhow::Result;
use chrono::Local;
use rusqlite::{Connection, params};
use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

/// 快照文件名。
///
/// 该文件位于工作区根目录，以便于 Git 版本控制的可见性。
/// 文件名固定为 `MEMORY_SNAPSHOT.md`，采用 Markdown 格式存储核心记忆。
pub const SNAPSHOT_FILENAME: &str = "MEMORY_SNAPSHOT.md";

/// 快照文件头部内容。
///
/// 写入每个快照文件顶部的固定头部信息，包含：
/// - 标题和说明
/// - 警告信息，提示用户不要手动编辑
/// - 自动水合的说明
const SNAPSHOT_HEADER: &str = "# 💡 VibeWindow Memory Snapshot\n\n\
    > Auto-generated by VibeWindow. Do not edit manually unless you know what you are doing.\n\
    > This file is the \"soul\" of your agent — if `brain.db` is lost, start the agent\n\
    > in this workspace and it will auto-hydrate from this file.\n\n";

/// 将所有核心记忆从 SQLite 数据库导出到 `MEMORY_SNAPSHOT.md` 文件。
///
/// 该函数会从工作区的 `memory/brain.db` 数据库中读取所有 `category = 'core'` 的记忆条目，
/// 并将其格式化为 Markdown 文档写入 `MEMORY_SNAPSHOT.md` 文件。
///
/// # 参数
///
/// * `workspace_dir` - 工作区目录路径，快照文件将创建在此目录下
///
/// # 返回值
///
/// 返回 `Result<usize>`，其中：
/// - `Ok(n)` 表示成功导出了 n 条记忆条目
/// - `Err(e)` 表示导出过程中发生错误
///
/// # 特殊情况
///
/// - 如果 `brain.db` 数据库不存在，返回 `Ok(0)`（不视为错误）
/// - 如果数据库中没有核心记忆，返回 `Ok(0)`
///
/// # 文件格式
///
/// 生成的 Markdown 文件包含：
/// - 文件头部和元数据（最后导出时间、总记忆数）
/// - 每条记忆的标题（以 `### 🔑` 开头）
/// - 记忆内容
/// - 时间戳（创建时间和更新时间）
///
/// # 示例
///
/// ```no_run
/// use std::path::Path;
/// use vibe_window::app::agent::memory::snapshot::export_snapshot;
///
/// let workspace = Path::new("/path/to/workspace");
/// match export_snapshot(workspace) {
///     Ok(count) => println!("导出了 {} 条核心记忆", count),
///     Err(e) => eprintln!("导出失败: {}", e),
/// }
/// ```
pub fn export_snapshot(workspace_dir: &Path) -> Result<usize> {
    // 构建数据库文件路径
    let db_path = workspace_dir.join("memory").join("brain.db");

    // 如果数据库不存在，直接返回 0（无需导出）
    if !db_path.exists() {
        tracing::debug!("snapshot export skipped: brain.db does not exist");
        return Ok(0);
    }

    // 打开数据库连接并配置 WAL 模式以提高并发性能
    let conn = Connection::open(&db_path)?;
    conn.execute_batch("PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL;")?;

    // 准备查询语句：获取所有核心记忆，按更新时间倒序排列
    let mut stmt = conn.prepare(
        "SELECT key, content, category, created_at, updated_at
         FROM memories
         WHERE category = 'core'
         ORDER BY updated_at DESC",
    )?;

    // 执行查询并收集所有行
    let rows: Vec<(String, String, String, String, String)> = stmt
        .query_map([], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?, row.get(4)?)))?
        .filter_map(|r| r.ok())
        .collect();

    // 如果没有核心记忆，返回 0
    if rows.is_empty() {
        tracing::debug!("snapshot export: no core memories to export");
        return Ok(0);
    }

    // 构建 Markdown 输出内容
    let mut output = String::with_capacity(rows.len() * 200);
    output.push_str(SNAPSHOT_HEADER);

    // 添加元数据：导出时间和总记忆数
    let now = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    write!(output, "**Last exported:** {now}\n\n").unwrap();
    write!(output, "**Total core memories:** {}\n\n---\n\n", rows.len()).unwrap();

    // 遍历每条记忆，格式化为 Markdown
    for (key, content, _category, created_at, updated_at) in &rows {
        write!(output, "### 🔑 `{key}`\n\n").unwrap();
        write!(output, "{content}\n\n").unwrap();
        write!(output, "*Created: {created_at} | Updated: {updated_at}*\n\n---\n\n").unwrap();
    }

    // 将内容写入快照文件
    let snapshot_path = snapshot_path(workspace_dir);
    fs::write(&snapshot_path, output)?;

    tracing::info!(
        "📸 Memory snapshot exported: {} core memories → {}",
        rows.len(),
        snapshot_path.display()
    );

    Ok(rows.len())
}

/// 从 `MEMORY_SNAPSHOT.md` 文件导入记忆到 SQLite 数据库。
///
/// 该函数在冷启动时被调用，当 `brain.db` 数据库不存在但快照文件存在时，
/// 会自动将快照中的记忆条目水合（hydrate）到新创建的数据库中。
///
/// # 参数
///
/// * `workspace_dir` - 工作区目录路径，快照文件和数据库都位于此目录下
///
/// # 返回值
///
/// 返回 `Result<usize>`，其中：
/// - `Ok(n)` 表示成功水合了 n 条记忆条目
/// - `Err(e)` 表示水合过程中发生错误
///
/// # 特殊情况
///
/// - 如果快照文件不存在，返回 `Ok(0)`（不视为错误）
/// - 如果快照文件为空或无法解析出有效条目，返回 `Ok(0)`
/// - 如果某条记忆的 key 已存在，会跳过该条目（使用 INSERT OR IGNORE）
///
/// # 数据库初始化
///
/// 该函数会自动创建必要的数据库表结构，包括：
/// - `memories` 表：存储记忆条目
/// - `memories_fts` 虚拟表：全文搜索索引
/// - `embedding_cache` 表：嵌入向量缓存
///
/// # 示例
///
/// ```no_run
/// use std::path::Path;
/// use vibe_window::app::agent::memory::snapshot::hydrate_from_snapshot;
///
/// let workspace = Path::new("/path/to/workspace");
/// match hydrate_from_snapshot(workspace) {
///     Ok(count) => println!("恢复了 {} 条核心记忆", count),
///     Err(e) => eprintln!("恢复失败: {}", e),
/// }
/// ```
pub fn hydrate_from_snapshot(workspace_dir: &Path) -> Result<usize> {
    // 检查快照文件是否存在
    let snapshot = snapshot_path(workspace_dir);
    if !snapshot.exists() {
        return Ok(0);
    }

    // 读取快照文件内容并解析
    let content = fs::read_to_string(&snapshot)?;
    let entries = parse_snapshot(&content);

    // 如果没有有效条目，直接返回
    if entries.is_empty() {
        return Ok(0);
    }

    // 确保记忆目录存在
    let db_dir = workspace_dir.join("memory");
    fs::create_dir_all(&db_dir)?;

    // 创建或打开数据库并配置 WAL 模式
    let db_path = db_dir.join("brain.db");
    let conn = Connection::open(&db_path)?;
    conn.execute_batch("PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL;")?;

    // 初始化数据库 schema（与 SqliteMemory::init_schema 保持一致）
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS memories (
            id         TEXT PRIMARY KEY,
            key        TEXT NOT NULL UNIQUE,
            content    TEXT NOT NULL,
            category   TEXT NOT NULL DEFAULT 'core',
            embedding  BLOB,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_mem_key ON memories(key);
        CREATE INDEX IF NOT EXISTS idx_mem_cat ON memories(category);
        CREATE INDEX IF NOT EXISTS idx_mem_updated ON memories(updated_at);

        CREATE VIRTUAL TABLE IF NOT EXISTS memories_fts
            USING fts5(key, content, content='memories', content_rowid='rowid');

        CREATE TABLE IF NOT EXISTS embedding_cache (
            content_hash TEXT PRIMARY KEY,
            embedding    BLOB NOT NULL,
            created_at   TEXT NOT NULL
        );",
    )?;

    // 记录当前时间戳（用于 created_at 和 updated_at）
    let now = Local::now().to_rfc3339();
    let mut hydrated = 0;

    // 逐条插入记忆条目
    for (key, content) in &entries {
        // 生成新的 UUID 作为主键
        let id = uuid::Uuid::new_v4().to_string();

        // 尝试插入记忆（如果 key 已存在则跳过）
        let result = conn.execute(
            "INSERT OR IGNORE INTO memories (id, key, content, category, created_at, updated_at)
             VALUES (?1, ?2, ?3, 'core', ?4, ?5)",
            params![id, key, content, now, now],
        );

        match result {
            Ok(changed) if changed > 0 => {
                // 插入成功，同时更新全文搜索索引
                let _ = conn.execute(
                    "INSERT INTO memories_fts(key, content) VALUES (?1, ?2)",
                    params![key, content],
                );
                hydrated += 1;
            }
            Ok(_) => {
                // key 已存在，跳过
                tracing::debug!("hydrate: key '{key}' already exists, skipping");
            }
            Err(e) => {
                // 插入失败，记录警告但继续处理下一条
                tracing::warn!("hydrate: failed to insert key '{key}': {e}");
            }
        }
    }

    tracing::info!(
        "🧬 Memory hydration complete: {} entries restored from {}",
        hydrated,
        snapshot.display()
    );

    Ok(hydrated)
}

/// 检查是否应该在启动时自动水合记忆。
///
/// 该函数用于判断是否需要从快照文件恢复记忆到数据库。
///
/// # 参数
///
/// * `workspace_dir` - 工作区目录路径
///
/// # 返回值
///
/// 返回 `true` 当满足以下两个条件时：
/// 1. `brain.db` 数据库不存在或为空（文件小于 4096 字节）
/// 2. `MEMORY_SNAPSHOT.md` 快照文件存在
///
/// # 实现细节
///
/// SQLite 数据库文件头至少需要 4096 字节，因此小于此大小的文件
/// 可以被认为是空数据库或损坏的数据库文件。
///
/// # 示例
///
/// ```no_run
/// use std::path::Path;
/// use vibe_window::app::agent::memory::snapshot::should_hydrate;
///
/// let workspace = Path::new("/path/to/workspace");
/// if should_hydrate(workspace) {
///     println!("需要从快照恢复记忆");
/// }
/// ```
pub fn should_hydrate(workspace_dir: &Path) -> bool {
    let db_path = workspace_dir.join("memory").join("brain.db");
    let snapshot = snapshot_path(workspace_dir);

    // 检查数据库是否缺失或为空
    let db_missing_or_empty = if db_path.exists() {
        // 数据库存在但可能为空（刚创建的情况）
        fs::metadata(&db_path)
            .map(|m| m.len() < 4096) // SQLite 文件头最小为 4096 字节
            .unwrap_or(true)
    } else {
        true
    };

    // 只有在数据库缺失/为空且快照存在时才需要水合
    db_missing_or_empty && snapshot.exists()
}

/// 获取快照文件的完整路径。
///
/// # 参数
///
/// * `workspace_dir` - 工作区目录路径
///
/// # 返回值
///
/// 返回快照文件的完整路径（工作区目录 + SNAPSHOT_FILENAME）
///
/// # 示例
///
/// ```no_run
/// use std::path::Path;
/// use vibe_window::app::agent::memory::snapshot::snapshot_path;
///
/// let workspace = Path::new("/my/workspace");
/// let path = snapshot_path(workspace);
/// assert_eq!(path.to_str().unwrap(), "/my/workspace/MEMORY_SNAPSHOT.md");
/// ```
fn snapshot_path(workspace_dir: &Path) -> PathBuf {
    workspace_dir.join(SNAPSHOT_FILENAME)
}

/// 解析结构化的 Markdown 快照文件，提取记忆条目。
///
/// 该函数将快照文件的内容解析为 (key, content) 元组列表。
///
/// # 参数
///
/// * `input` - 快照文件的完整文本内容
///
/// # 返回值
///
/// 返回 `Vec<(String, String)>`，每个元组包含：
/// - 第一个元素：记忆的键（key）
/// - 第二个元素：记忆的内容（content）
///
/// # 解析规则
///
/// 1. 识别格式为 `### 🔑 \`key_name\`` 的标题行作为记忆键
/// 2. 收集该标题下的所有内容，直到下一个标题或文件结束
/// 3. 跳过元数据行（以 `*Created:` 开头）和分隔符（`---`）
/// 4. 保留内容中的空行和格式
///
/// # 示例
///
/// ```
/// use vibe_window::app::agent::memory::snapshot::parse_snapshot;
///
/// let markdown = r#"
/// ### 🔑 `favorite_color`
///
/// My favorite color is blue.
///
/// *Created: 2024-01-01 | Updated: 2024-01-02*
///
/// ---
///
/// ### 🔑 `favorite_food`
///
/// I love pizza.
/// "#;
///
/// let entries = parse_snapshot(markdown);
/// assert_eq!(entries.len(), 2);
/// assert_eq!(entries[0].0, "favorite_color");
/// assert_eq!(entries[1].0, "favorite_food");
/// ```
fn parse_snapshot(input: &str) -> Vec<(String, String)> {
    let mut entries = Vec::new();
    let mut current_key: Option<String> = None;
    let mut current_content = String::new();

    // 逐行解析 Markdown 内容
    for line in input.lines() {
        let trimmed = line.trim();

        // 匹配标题格式：### 🔑 `key_name`
        if trimmed.starts_with("### 🔑 `") && trimmed.ends_with('`') {
            // 保存前一条记忆（如果存在）
            if let Some(key) = current_key.take() {
                let content = current_content.trim().to_string();
                if !content.is_empty() {
                    entries.push((key, content));
                }
            }

            // 提取新的键名
            let key = trimmed
                .strip_prefix("### 🔑 `")
                .and_then(|s| s.strip_suffix('`'))
                .unwrap_or("")
                .to_string();

            if !key.is_empty() {
                current_key = Some(key);
                current_content = String::new();
            }
        } else if current_key.is_some() {
            // 跳过元数据行和分隔符
            if trimmed.starts_with("*Created:") || trimmed == "---" {
                continue;
            }
            // 累积内容（保留原始行格式）
            if !current_content.is_empty() || !trimmed.is_empty() {
                if !current_content.is_empty() {
                    current_content.push('\n');
                }
                current_content.push_str(line);
            }
        }
    }

    // 处理最后一条记忆（文件末尾可能没有下一个标题）
    if let Some(key) = current_key {
        let content = current_content.trim().to_string();
        if !content.is_empty() {
            entries.push((key, content));
        }
    }

    entries
}

#[cfg(test)]
#[path = "tests.rs"]
mod tests;
