//! 快照模块的单元测试
//!
//! 本模块提供对 memory/snapshot 功能的完整测试覆盖，包括：
//! - 快照文件解析（从 Markdown 格式提取记忆条目）
//! - 快照导出（将核心记忆持久化为 Markdown 文件）
//! - 快照水合/恢复（从快照文件重建数据库）
//! - 边界条件与错误路径验证
//!
//! 测试策略：
//! - 使用 `tempfile` crate 创建隔离的临时工作区，确保测试之间互不干扰
//! - 采用端到端测试风格，验证从数据库到快照文件的完整往返
//! - 覆盖正常路径、空状态、多行内容、过滤非核心记忆等场景

use super::*;
use tempfile::TempDir;

/// 测试基础快照解析功能
///
/// 验证点：
/// - 能够正确解析包含 2 个核心记忆的标准 Markdown 快照格式
/// - 提取的键（key）与预期一致（identity, preference_lang）
/// - 提取的内容包含预期关键词（self-preserving, Rust）
/// - 解析器能跳过元数据部分（导出时间、总数等）
#[test]
fn parse_snapshot_basic() {
    let input = r#"# 💡 VibeWindow Memory Snapshot

> Auto-generated by VibeWindow.

**Last exported:** 2025-01-15 14:30:00

**Total core memories:** 2

---

### 🔑 `identity`

I am VibeWindow, a self-preserving AI agent.

*Created: 2025-01-15 | Updated: 2025-01-15*

---

### 🔑 `preference_lang`

The user prefers Rust for systems programming.

*Created: 2025-01-14 | Updated: 2025-01-15*

---
"#;

    let entries = parse_snapshot(input);
    assert_eq!(entries.len(), 2);
    assert_eq!(entries[0].0, "identity");
    assert!(entries[0].1.contains("self-preserving"));
    assert_eq!(entries[1].0, "preference_lang");
    assert!(entries[1].1.contains("Rust"));
}

/// 测试空快照的解析
///
/// 验证点：
/// - 当快照文件只包含元数据头部而没有记忆条目时，应返回空列表
/// - 解析器不会因缺少条目而 panic 或返回错误
#[test]
fn parse_snapshot_empty() {
    let input = "# 💡 VibeWindow Memory Snapshot\n\n> Nothing here.\n";
    let entries = parse_snapshot(input);
    assert!(entries.is_empty());
}

/// 测试多行内容的快照解析
///
/// 验证点：
/// - 能够正确解析包含多行文本的记忆内容
/// - 多行内容中的换行符应被保留
/// - 验证示例中的三条规则都能被完整提取
#[test]
fn parse_snapshot_multiline_content() {
    let input = r#"### 🔑 `rules`

Rule 1: Always be helpful.
Rule 2: Never lie.
Rule 3: Protect the user.

*Created: 2025-01-15 | Updated: 2025-01-15*

---
"#;

    let entries = parse_snapshot(input);
    assert_eq!(entries.len(), 1);
    assert!(entries[0].1.contains("Rule 1"));
    assert!(entries[0].1.contains("Rule 3"));
}

/// 测试在数据库不存在时导出快照的行为
///
/// 验证点：
/// - 当工作区中没有 brain.db 时，导出操作应成功返回计数 0
/// - 不应因数据库缺失而返回错误
/// - 快照文件不会被创建（因为没有数据需要导出）
#[test]
fn export_no_db_returns_zero() {
    let tmp = TempDir::new().unwrap();
    let count = export_snapshot(tmp.path()).unwrap();
    assert_eq!(count, 0);
}

/// 测试完整的导出-水合往返流程
///
/// 这是快照功能的核心端到端测试，模拟完整的灾难恢复场景：
/// 1. 创建包含核心记忆的数据库
/// 2. 导出快照文件
/// 3. 模拟数据库丢失（删除 brain.db）
/// 4. 从快照文件恢复数据
///
/// 验证点：
/// - 只有核心记忆（category='core'）被导出，非核心记忆被过滤
/// - 导出的快照文件包含预期的 Markdown 格式和内容
/// - should_hydrate 能正确检测需要恢复的场景
/// - 水合操作能完整恢复所有核心记忆
/// - 恢复后的数据库包含正确的数据结构和内容
#[test]
fn export_and_hydrate_roundtrip() {
    let tmp = TempDir::new().unwrap();
    let workspace = tmp.path();
    let storage = paths::project_data_dir(workspace).unwrap();

    // 手动创建包含核心记忆的 brain.db 数据库
    let db_dir = storage.join("memory");
    fs::create_dir_all(&db_dir).unwrap();
    let db_path = db_dir.join("brain.db");

    // 初始化数据库 schema 和 WAL 模式
    let conn = Connection::open(&db_path).unwrap();
    conn.execute_batch(
        "PRAGMA journal_mode = WAL;
         CREATE TABLE IF NOT EXISTS memories (
            id TEXT PRIMARY KEY,
            key TEXT NOT NULL UNIQUE,
            content TEXT NOT NULL,
            category TEXT NOT NULL DEFAULT 'core',
            embedding BLOB,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
         );
         CREATE INDEX IF NOT EXISTS idx_mem_key ON memories(key);",
    )
    .unwrap();

    // 插入两条核心记忆用于测试导出
    let now = Local::now().to_rfc3339();
    conn.execute(
        "INSERT INTO memories (id, key, content, category, created_at, updated_at)
         VALUES ('id1', 'identity', 'I am a test agent', 'core', ?1, ?2)",
        params![now, now],
    )
    .unwrap();
    conn.execute(
        "INSERT INTO memories (id, key, content, category, created_at, updated_at)
         VALUES ('id2', 'preference', 'User likes Rust', 'core', ?1, ?2)",
        params![now, now],
    )
    .unwrap();
    // 插入一条非核心记忆（对话类型），验证其不会被导出
    conn.execute(
        "INSERT INTO memories (id, key, content, category, created_at, updated_at)
         VALUES ('id3', 'conv1', 'Random convo', 'conversation', ?1, ?2)",
        params![now, now],
    )
    .unwrap();
    drop(conn);

    // 执行快照导出
    let exported = export_snapshot(workspace).unwrap();
    assert_eq!(exported, 2, "应仅导出核心记忆");

    // 验证快照文件已创建且内容正确
    let snapshot = storage.join(SNAPSHOT_FILENAME);
    assert!(snapshot.exists());
    let content = fs::read_to_string(&snapshot).unwrap();
    assert!(content.contains("identity"));
    assert!(content.contains("I am a test agent"));
    assert!(content.contains("preference"));
    assert!(!content.contains("Random convo"));

    // 模拟灾难性故障：删除 brain.db 文件
    fs::remove_file(&db_path).unwrap();
    assert!(!db_path.exists());

    // 验证 should_hydrate 能检测到需要恢复的场景
    assert!(should_hydrate(workspace));

    // 从快照文件执行水合恢复
    let hydrated = hydrate_from_snapshot(workspace).unwrap();
    assert_eq!(hydrated, 2, "应恢复两条核心记忆");

    // 验证 brain.db 已被重新创建
    assert!(db_path.exists());

    // 验证恢复后的数据库包含正确的数据
    let conn = Connection::open(&db_path).unwrap();
    let count: i64 = conn.query_row("SELECT COUNT(*) FROM memories", [], |row| row.get(0)).unwrap();
    assert_eq!(count, 2);

    // 验证具体的记忆内容
    let identity: String = conn
        .query_row("SELECT content FROM memories WHERE key = 'identity'", [], |row| row.get(0))
        .unwrap();
    assert_eq!(identity, "I am a test agent");
}

/// 测试 should_hydrate 函数的条件判断逻辑
///
/// should_hydrate 应仅在以下条件同时满足时返回 true：
/// - 快照文件存在
/// - 数据库文件不存在（需要恢复）
///
/// 验证场景：
/// 1. 无数据库、无快照 → false（无需恢复）
/// 2. 有快照、无数据库 → true（需要恢复）
/// 3. 有数据库、有快照 → false（数据库已存在，无需恢复）
#[test]
fn should_hydrate_only_when_needed() {
    let tmp = TempDir::new().unwrap();
    let workspace = tmp.path();
    let storage = paths::project_data_dir(workspace).unwrap();

    // 场景 1：无数据库、无快照 → 应返回 false
    assert!(!should_hydrate(workspace));

    // 场景 2：创建快照但没有数据库 → 应返回 true
    let snapshot = storage.join(SNAPSHOT_FILENAME);
    fs::create_dir_all(&storage).unwrap();
    fs::write(&snapshot, "### 🔑 `test`\n\nHello\n").unwrap();
    assert!(should_hydrate(workspace));

    // 场景 3：创建真实数据库 → 应返回 false（即使快照存在）
    let db_dir = storage.join("memory");
    fs::create_dir_all(&db_dir).unwrap();
    let db_path = db_dir.join("brain.db");
    let conn = Connection::open(&db_path).unwrap();
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS memories (
            id TEXT PRIMARY KEY,
            key TEXT NOT NULL UNIQUE,
            content TEXT NOT NULL,
            category TEXT NOT NULL DEFAULT 'core',
            embedding BLOB,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
         );
         INSERT INTO memories VALUES('x','x','x','core',NULL,'2025-01-01','2025-01-01');",
    )
    .unwrap();
    drop(conn);
    assert!(!should_hydrate(workspace));
}

/// 测试在快照文件不存在时执行水合操作的行为
///
/// 验证点：
/// - 当工作区中没有快照文件时，水合操作应成功返回计数 0
/// - 不应因快照文件缺失而返回错误
/// - 数据库不会被创建或修改（因为没有数据需要恢复）
#[test]
fn hydrate_no_snapshot_returns_zero() {
    let tmp = TempDir::new().unwrap();
    let count = hydrate_from_snapshot(tmp.path()).unwrap();
    assert_eq!(count, 0);
}
